version: '3.9'

services:
  postgres:
    image: postgres:14.11-alpine3.18
    restart: always
    container_name: postgres4
    ports:
      - 5432:5432
    env_file:
    - DeploymentTools/docker/docker.env
    networks:
    - project-net
    volumes:
      - myshoo-volume:/var/lib/postgresql/data
    hostname: postgresdb
  
  shoe-mart:
    image:  abdulrahimom/shoe-mart:1.2
    build: .
    restart: always
    container_name: shoe-mart4
    depends_on:
      - postgres
    ports:
      - 4000:4000
    networks:
    - project-net
    volumes:
      - myshoo-volume:/var/lib/postgresql/data

volumes:
  myshoo-volume:

networks:
  project-net:
    driver : bridge